### PR TITLE
[cli] Refactor setup

### LINKED ISSUE #4596: [cli] Fails to install example when passing a directory
- When passing in a non-default option in the path argument or option and passing in an example through `--example`, the CLI fails to create the required folder
- Introduced in https://github.com/mui/toolpad/pull/4434

### PR DESCRIPTION
**Pull request by bharatkashyap**
- Separate the CLI `index` code into separate files
- Fix #4596
- Adds better post-install instructions when installing examples using `--example`

### CODE REVIEW

File: packages/create-toolpad-app/src/core.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+  // eslint-disable-next-line no-console
+  console.log();
+  // eslint-disable-next-line no-console
+  console.log(
+    `${chalk.cyan('info')} - Creating Toolpad Core project in ${chalk.cyan(options.absolutePath)}`,
+  );
+  // eslint-disable-next-line no-console
+  console.log();
+
+  const pkg = await findCtaPackageJson();
```
Comment (Janpot) [inline packages/create-toolpad-app/src/core.ts:18]: Better to remove this call and pass the version as an option.

File: packages/create-toolpad-app/src/package.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+      return 'pnpm';
+    }
+    if (userAgent.startsWith('npm')) {
+      return 'npm';
+    }
+  }
+  return 'pnpm';
+}
+
+export async function findCtaPackageJson() {
```
Comment (Janpot) [inline packages/create-toolpad-app/src/package.ts:22]: There exist package json types in this workspace already. Should add a return type here.

**Review by Janpot — APPROVED** [review]
Few small suggestions. Otherwise seems to be good. 👍

File: packages/create-toolpad-app/src/core.ts (hunk 1 above)
Comment (bharatkashyap) [reply packages/create-toolpad-app/src/core.ts:18]: If we remove the call, how would we set the default value of the version in case nothing is passed in the version option?

Comment (Janpot) [reply packages/create-toolpad-app/src/core.ts:18]: If there is no sensible default, then you make the option mandatory
