### PR TITLE
[core] Add `LocalizationProvider`

### LINKED ISSUE #4565: Enable localization injection from outside for all texts
### Summary

It would be nice to avoid hard-coded English texts, and allow localization.

### Examples

example of hard-coded English text: https://github.com/mui/toolpad/blob/master/packages/toolpad-core/src/SignInPage/SignInPage.tsx#L349

### Motivation

I am building a dashboard in another language.

**Search keywords**: localize, translate, lang

### LINKED ISSUE #4673: Allow text change on SignIn button
### Steps to reproduce

Steps:
1. Open this link to live example: [demo](https://codesandbox.io/p/sandbox/charming-agnesi-fd7yvt)

### Current behavior

The content of the SignIn button can't be changed through submitButton slot props

### Expected behavior

We should be able to change the text to allow localization

### Context

localization

### Your environment

_No response_

**Search keywords**: localization signin

### PR DESCRIPTION
**Pull request by bharatkashyap**
### Breaking Change

- Rename some existing localization keys on the `Account` component to make them part of the global `LocaleText`
- `signInLabel` -> `accountSignInLabel`
- `signOutLabel` -> `accountSignOutLabel`
- `iconButtonAriaLabel` -> `accountPreviewIconButtonLabel`

- Closes #4565 
- Closes #4673

### CODE REVIEW

File: docs/data/toolpad/core/components/account/AccountCustomLocaleText.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import * as React from 'react';
-import { AuthenticationContext, SessionContext } from '@toolpad/core/AppProvider';
+import { AppProvider } from '@toolpad/core/AppProvider';
```
Comment (bharatkashyap) [inline docs/data/toolpad/core/components/account/AccountCustomLocaleText.js:2]: This is a clean up on the demo (since none of the demos on this page were using the `Account` component inside the `AppProvider` - added that to one example to demonstrate a local override of the `localization`)

File: docs/data/toolpad/core/introduction/base-concepts.md [hunk 2]
```diff
@@ -105,3 +105,124 @@ In this example:
...
+```tsx
+import { createTheme, ThemeProvider } from '@mui/material/styles';
+import hiIN from '@toolpad/core/locales/hiIN';
+
+const theme = createTheme({
+   {
+    palette: {
+      primary: { main: '#1976d2' },
+    },
+  },
```
Comment (Janpot) [inline docs/data/toolpad/core/introduction/base-concepts.md:130]: Should we add core locale as well? That would be the user's intent, likely, rigth?

File: docs/pages/toolpad/core/api/app-provider.json [hunk 3]
```diff
@@ -12,6 +12,12 @@
       },
       "default": "null"
     },
+    "localeText": {
+      "type": {
+        "name": "shape",
+        "description": "{ accountPreviewIconButtonLabel?: string, accountPreviewTitle?: string, accountSignInLabel?: string, accountSignOutLabel?: string, alert?: string, cancel?: string, close?: string, confirm?: string, delete?: string, email?: string, loading?: string, magicLinkSignInTitle?: string, oauthSignInTitle?: string, ok?: string, or?: string, passkey?: string, passkeySignInTitle?: string, password?: string, save?: string, signInRememberMe?: string, signInSubtitle?: string, signInTitle?: string, to?: string, username?: string, with?: string }"
```
Comment (Janpot) [inline docs/pages/toolpad/core/api/app-provider.json:18]: This won't scale. Any way we can do the same as [X](https://github.com/mui/mui-x/blob/b252b9a9562a69512b74d3cb89049be5591d908b/docs/pages/x/api/date-pickers/static-time-picker.json#L15)?

File: packages/toolpad-core/src/AppProvider/AppProvider.tsx [hunk 4]
```diff
@@ -202,6 +210,36 @@ AppProvider.propTypes /* remove-proptypes */ = {
    * The content of the app provider.
    */
   children: PropTypes.node,
+  /**
+   * Locale text for components
+   */
+  localeText: PropTypes.shape({
```
Comment (Janpot) [inline packages/toolpad-core/src/AppProvider/AppProvider.tsx:216]: Same scaling issue here
